services:
  srv_bunkerweb:
    hostname: srv_bunkerweb
    image:   bunkerity/bunkerweb-all-in-one:1.6.6
    restart: no
    container_name: srv_bunkerweb
    cap_add: [ "NET_ADMIN" ]
    network_mode: host
    dns: [ $SUBNET_SERVERS.$DNS_SRV_IP ]
    volumes:
      - bw_conf:/etc/bunkerweb
      - bw_data:/var/lib/bunkerweb

volumes:
  bw_conf:
  bw_data:    
